"""feat_documentos_clinicos

Revision ID: 8adcccf53299
Revises: 99b27f752394
Create Date: 2026-07-12 13:23:11.993439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8adcccf53299'
down_revision: Union[str, Sequence[str], None] = '99b27f752394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('care_recipient_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['care_recipient_id'], ['care_recipients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['care_group_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_documents_care_recipient_id'), 'clinical_documents', ['care_recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_documents_care_recipient_id'), table_name='clinical_documents')
    op.drop_table('clinical_documents')
    # ### end Alembic commands ###
