"""Initial models

Revision ID: 8f8f73767996
Revises: 
Create Date: 2026-06-06 20:01:32.011285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f8f73767996'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_group_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('care_group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUPPORT', name='userrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['care_group_id'], ['care_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_group_members_user_id'), 'care_group_members', ['user_id'], unique=False)
    op.create_table('care_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('care_group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('blood_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('emergency_contacts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['care_group_id'], ['care_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_group_id')
    )
    op.create_table('medication_protocols',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('care_recipient_id', sa.Uuid(), nullable=False),
    sa.Column('medication_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('frequency_interval_hours', sa.Integer(), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('safety_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['care_recipient_id'], ['care_recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('care_group_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('recurrence_rule', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['care_group_members.id'], ),
    sa.ForeignKeyConstraint(['care_group_id'], ['care_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('protocol_id', sa.Uuid(), nullable=False),
    sa.Column('administered_by', sa.Uuid(), nullable=False),
    sa.Column('administered_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['care_group_members.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['medication_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('medication_protocols')
    op.drop_table('care_recipients')
    op.drop_index(op.f('ix_care_group_members_user_id'), table_name='care_group_members')
    op.drop_table('care_group_members')
    op.drop_table('care_groups')
    # ### end Alembic commands ###
